import Button from "@components/Button";
import HeaderBack from "@components/HeaderBack";
import Layout from "@components/Layout";
import React from "react";
import Input from "@components/Input";
import { FiUser } from "react-icons/fi";
import { RiLockPasswordLine } from "react-icons/ri";
import { FcGoogle } from "react-icons/fc";
import Link from "next/link";
import { getProviders, signIn } from "next-auth/react";
import { useRouter } from "next/router";
